=== yedg/mybatis-plugin/src/main/resources/com/tqlab/plugin/mybatis/tqlab-mybatis-plugin.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema xmlns="http://schema.tqlab.com/mybatis"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://schema.tqlab.com/mybatis">
    
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace"/>
    
    <xsd:annotation>
        <xsd:documentation>
            <![CDATA[
            Mybatis generator sql template Schema. 
            ]]>
        </xsd:documentation>
    </xsd:annotation>
    
    <xsd:element name="property">
        <xsd:complexType>
            <xsd:attribute name="column" type="xsd:NCName" use="required"/>
            <xsd:attribute name="javaProperty" type="xsd:NCName" use="required"/>
            <xsd:attribute name="javaType" type="JavaFullClassName" use="required"/>
            <xsd:attribute name="defaultValue" type="xsd:NCName"/>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="result">
        <xsd:complexType>
            <xsd:sequence minOccurs="1" maxOccurs="unbounded">
                <xsd:element ref="property"/>
            </xsd:sequence>
            <xsd:attribute name="objectName" type="JavaFullClassName" use="required" />
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="column">
        <xsd:complexType>
            <xsd:attribute name="name" type="xsd:NCName" use="required" >
                <xsd:annotation>
                    <xsd:documentation>
                        <![CDATA[
                    Specify a specific java property of the column
                    ]]>
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="javaType" type="JavaFullClassName" use="required" />
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="param" type="MapperParam">
        <xsd:annotation>
            <xsd:documentation>
                <![CDATA[
                Specify certain parameters for Mybatis Mapper function. For example #{keyword,jdbcType=VARCHAR} .
                ]]>
            </xsd:documentation>
        </xsd:annotation>
    </xsd:element>
    
    <xsd:element name="params">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="param" minOccurs="1" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="option">
        <xsd:complexType>
            <xsd:attribute name="name" type="xsd:NCName" use="required" >
                <xsd:annotation>
                    <xsd:documentation>
                        <![CDATA[
                        Option name, useCache, flushCache, resultSetType, statementType, fetchSize, timeout, useGeneratedKeys, keyProperty, keyColumn etc.
                        ]]>
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="value" type="xsd:string" use="required" />
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="options">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="option" minOccurs="1" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="sql" type="Sql">
        <xsd:annotation>
            <xsd:documentation>
                <![CDATA[
                For example, use mybatis origin SQL Mapping :
                <![CDATA[
     			<script>
     				select * test_db where id in 
     				<foreach item="idList" index="index" collection="list" open="(" separator="," close=")">
     					#{idList,jdbcType=ARRAY}
     				</foreach>
     				order by id desc
     			</script>
			    ]] >;
                ]]>
            </xsd:documentation>
        </xsd:annotation>
    </xsd:element>
    
    <xsd:element name="comment" type="xsd:string">
        
    </xsd:element>
    
    <xsd:element name="operation">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="comment" minOccurs="0" maxOccurs="1" />
                <xsd:element ref="params" minOccurs="0" maxOccurs="1" />
                <xsd:element ref="options" minOccurs="0" maxOccurs="1" />
                <xsd:element ref="result" minOccurs="0" maxOccurs="1"/>
                <xsd:element ref="sql" minOccurs="1" maxOccurs="1" />
            </xsd:sequence>
            <xsd:attribute name="id" type="xsd:ID" use="required">
                <xsd:annotation>
                    <xsd:documentation>
                        <![CDATA[ 
                        The unique identifier for a mybatis Mapper. 
                        ]]>
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="many" type="xsd:boolean" default="true"/>
            <xsd:attribute name="resultType" type="JavaFullClassName" use="optional" />
            <xsd:attribute name="parameterType" type="JavaFullClassName" use="optional" />
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="sqlFragment">
        <xsd:complexType mixed="true">
            <xsd:attribute name="id" type="xsd:ID" use="required">
                <xsd:annotation>
                    <xsd:documentation>
                        <![CDATA[ 
                        The unique identifier for a sql fragment. 
                        ]]>
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
        </xsd:complexType>
    </xsd:element>
    
    <!--  Top-level <table> tag  -->
    <xsd:element name="table">
        <xsd:annotation>
            <xsd:documentation>
                <![CDATA[
                The table to generate Mybatis java Mapper.
                ]]>
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="column" minOccurs="0" maxOccurs="unbounded" />
                <xsd:element ref="result" minOccurs="0" maxOccurs="unbounded" />
                <xsd:element ref="sqlFragment" minOccurs="0" maxOccurs="unbounded" />
                <xsd:element ref="operation" minOccurs="1" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:attribute name="name" type="xsd:NCName" use="required"/>
            <xsd:attribute name="sqlSessionFactory" type="xsd:NCName"/>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:simpleType name="JavaFullClassName">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="([A-Za-z_]+[0-9]*\.)*([A-Za-z_])[a-zA-Z0-9_]*"></xsd:pattern>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="MapperParam">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="#\{[A-Za-z_]+[a-zA-z0-9_]*\s*,\s*jdbcType=[A-Z_]+\}"></xsd:pattern>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="Sql">
        <xsd:annotation>
            <xsd:documentation>
                <![CDATA[
                Sql Type
                ]]>
            </xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[\s\S]+"></xsd:pattern>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== yedg/mybatis-plugin/demo/src/main/resources/sqltemplate/hsqldb/table.star.xml
<?xml version="1.0" encoding="UTF-8"?>
<table xmlns="http://schema.tqlab.com/mybatis" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://schema.tqlab.com/mybatis http://schema.tqlab.com/mybatis/tqlab-mybatis-plugin.xsd"
	name="star">

	<result objectName="StarMovies">
		<property column="id" javaProperty="id" javaType="java.lang.Integer" />
		<property column="firstname" javaProperty="firstname"
			javaType="java.lang.String" />
		<property column="lastname" javaProperty="lastname" javaType="java.lang.String" />
		<property column="movieid" javaProperty="movieid" javaType="java.lang.Integer" />
		<property column="title" javaProperty="title" javaType="java.lang.String" />
	</result>

	<operation id="deleteById">
		<sql>
			<![CDATA[
			delete from star where id=#{id,jdbcType=INTEGER};
			]]>
		</sql>
	</operation>

	<operation id="count" many="false" resultType="int">
		<sql>
			<![CDATA[
			select count(*) from star;
			]]>
		</sql>
	</operation>

	<operation id="sum" many="false"  resultType="java.lang.Integer">
		<sql>
			<![CDATA[
			select sum(id) from star;
			]]>
		</sql>
	</operation>

	<operation id="selectAll" many="true">
		<sql>
			<![CDATA[
			select * from star;
			]]>
		</sql>
	</operation>

	<operation id="selectById" many="false">
		<sql>
			<![CDATA[
			select * from star where id=#{id,jdbcType=INTEGER};
			]]>
		</sql>
	</operation>

	<operation id="selectWithPagination">
		<comment>
			demo
		</comment>
		<sql>
			<![CDATA[
			select * from star limit #{size,jdbcType=INTEGER} OFFSET #{offset,jdbcType=INTEGER}
			]]>
		</sql>
	</operation>

	<operation id="selectComplex1" resultType="StarMovies" many="true">
		<sql>
			<![CDATA[
			select a.*, b.* from star a, movies b where a.id = b.starid
			]]>
		</sql>
	</operation>

	<operation id="selectComplex2" many="true">
		<result objectName="StarMovies2">
			<property column="star_id" javaProperty="id" javaType="java.lang.Integer" />
			<property column="name" javaProperty="firstname" javaType="java.lang.String" />
			<property column="lastname" javaProperty="lastname"
				javaType="java.lang.String" />
			<property column="movieid" javaProperty="movieid" javaType="java.lang.Integer" />
			<property column="title" javaProperty="title" javaType="java.lang.String" />
		</result>
		<sql>
			<![CDATA[
			select a.id as star_id, a.firstname as name, a.lastname, 
			b.movieid, b.title from star a, movies b 
			where a.id = b.starid
			]]>
		</sql>
	</operation>

	<operation id="searchByfirstname" many="true">
		<params>
			<param>#{obj,jdbcType=JAVA_OBJECT}</param>
		</params>
		<sql>
			<![CDATA[
				<script>
				<bind name="pattern" value="'%' + firstname + '%'" />
				select * from star where firstname like #{pattern} and id = #{id};
				</script>
			]]>
		</sql>
	</operation>

	<operation id="update">
		<params>
			<param>#{firstname,jdbcType=VARCHAR}</param>
			<param>#{lastname,jdbcType=VARCHAR}</param>
			<param>#{id,jdbcType=INTEGER}</param>
		</params>
		<sql>
		<![CDATA[
		<script>
		  update star
		    <set>
		      <if test="firstname!= null">firstname=#{firstname},</if>
		      <if test="lastname!= null">lastname=#{lastname},</if>
		    </set>
		  where id=#{id}
		</script>
		]]>
		</sql>
	</operation>

	<operation id="update2">
		<sql>
		<![CDATA[
		<script>
		  update star
		    <set>
		      <if test="firstname!= null">firstname=#{firstname},</if>
		      <if test="lastname!= null">lastname=#{lastname},</if>
		    </set>
		  where id=#{id}
		</script>
		]]>
		</sql>
	</operation>
</table>
